export const SETUP_POPULATION_TOKENS = 6
export const SETUP_SURVIVAL_TOKENS = 24
export const SETUP_SPECIES_STARTING_EACH_TRAIT_IN_GENOME = 2
export const SETUP_SPECIES_STARTING_ADAPTATIONS = 2
export const SETUP_LOCATION_STARTING_FAUNA = 3
export const SETUP_LOCATION_STARTING_FLORA = 2